GET http://localhost:5000/api/recipes HTTP/1.1
content-type: application/json

{
    "name":"_end22r_y",
    "recipeId": 1,
    "description": "12312desc12"
}


# POST http://localhost:5000/api/recipes HTTP/1.1
# content-type: application/json

# {
#     "name":"_end22r_y",
#     "recipeId": 1,
#     "description": "12312desc12"
# }



# PUT http://localhost:5000/api/recipes HTTP/1.1
# content-type: application/json

# {
#     "name":"_end22r_y",
#     "recipeId": 1,
#     "description": "12312desc12"
# }

# DELETE  http://localhost:5000/api/recipes HTTP/1.1
# content-type: application/json

# {
#     "name":"_end22r_y",
#     "recipeId": 1,
#     "description": "12312desc12"
# }

